config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/alumnos/filtro' => 'alumnos#filtro' # or match for older Rails versions
  get '/alumnos/tutores' => 'alumnos#tutores' # or match for older Rails versions
  get '/alumnos/tutor' => 'alumnos#tutor' # or match for older Rails versions
  get '/alumnos/busqueda' => 'alumnos#busqueda' # or match for older Rails versions
  resources :maestros
  resources :alumnos

  root 'welcome#index'

end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
	validates :nombre, presence: true
	validates :ap_paterno, presence: true
	validates :ap_materno, presence: true
	validates :sexo, presence: true
	validates :curp, presence: true, length: { is: 18 }
	validates :fecha_nacimiento, presence: true
	validates :grado, presence: true
	validates :grupo, presence: true
	validates :nombre_tutor, presence: true
	validates :ap_paterno_tutor, presence: true
	validates :ap_materno_tutor, presence: true
	validates :direccion, presence: true
	validates :telefono, presence: true,numericality: { only_integer: true }
end

app/models/maestro.rb
class Maestro < ActiveRecord::Base
	validates :nombre_m, presence: true
	validates :ap_materno_m, presence: true
	validates :ap_paterno_m, presence: true
	validates :direccion_m, presence: true
	validates :grado_m, presence: true
	validates :grupo_m, presence: true
	validates :telefono_m, presence: true,numericality: { only_integer: true }
end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController 
  before_action :set_alumno, only: [:show, :edit, :update, :destroy]

  # GET /alumnos
  # GET /alumnos.json
  def index
    @alumnos = Alumno.all

    
    #@alumnos = Alumno.where(grado: '1', grupo: 'A')
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
  end

  def tutores
    @alumnos = Alumno.all
  end

  def tutor

  end

  def busqueda
      @nombre= params[:nombre]
      @ap_paterno =params[:ap_paterno]
      @ap_materno =params[:ap_materno]

      if params[:nombre]
      @alumnos = Alumno.where(nombre:@nombre,ap_paterno:@ap_paterno,ap_materno:@ap_materno)
      else
      @alumnos = Alumno.all
    end
  end

  def filtro
    @grado_alumno = params[:grado]
    @grupo_alumno = params[:grupo]

    if params[:grado]
      @alumnos = Alumno.where(grado:@grado_alumno,grupo:@grupo_alumno)
    else
      @alumnos = Alumno.all
    end
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    @alumno = Alumno.new(alumno_params)
    @alumno.nombre=@alumno.nombre.capitalize
    @alumno.ap_paterno=@alumno.ap_paterno.capitalize
    @alumno.ap_materno=@alumno.ap_materno.capitalize
    @alumno.nombre_tutor=@alumno.nombre_tutor.capitalize
    @alumno.ap_paterno_tutor=@alumno.ap_paterno_tutor.capitalize
    @alumno.ap_materno_tutor=@alumno.ap_materno_tutor.capitalize


    respond_to do |format|
      if @alumno.save
        format.html { redirect_to @alumno, notice: 'Alumno registrado correctamente .' }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1
  # PATCH/PUT /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to @alumno, notice: 'Registro de Alumno actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno.destroy
    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: 'Registro de Alumno eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alumno_params
      params.require(:alumno).permit(:nombre, :ap_paterno, :ap_materno, :sexo, :curp, :fecha_nacimiento, :grado, :grupo, :nombre_tutor, :ap_paterno_tutor, :ap_materno_tutor, :direccion, :telefono)
    end







end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maestros_controller.rb
class MaestrosController < ApplicationController
  before_action :set_maestro, only: [:show, :edit, :update, :destroy]

  # GET /maestros
  # GET /maestros.json
  def index
    @maestros = Maestro.all
  end

  # GET /maestros/1
  # GET /maestros/1.json
  def show
  end

  # GET /maestros/new
  def new
    @maestro = Maestro.new
  end

  # GET /maestros/1/edit
  def edit
  end

  # POST /maestros
  # POST /maestros.json
  def create
    @maestro = Maestro.new(maestro_params)
    @maestro.nombre_m =@maestro.nombre_m.capitalize
    @maestro.ap_paterno_m =@maestro.ap_paterno_m.capitalize
    @maestro.ap_materno_m =@maestro.ap_materno_m.capitalize
    
    respond_to do |format|
      if @maestro.save
        format.html { redirect_to @maestro, notice: 'Registro de Maestro actualizado correctamente.' }
        format.json { render :show, status: :created, location: @maestro }
      else
        format.html { render :new }
        format.json { render json: @maestro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maestros/1
  # PATCH/PUT /maestros/1.json
  def update
    respond_to do |format|
      if @maestro.update(maestro_params)
        format.html { redirect_to @maestro, notice: 'Registro de Maestro actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @maestro }
      else
        format.html { render :edit }
        format.json { render json: @maestro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maestros/1
  # DELETE /maestros/1.json
  def destroy
    @maestro.destroy
    respond_to do |format|
      format.html { redirect_to maestros_url, notice: 'Registro de Maestro eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maestro
      @maestro = Maestro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maestro_params
      params.require(:maestro).permit(:nombre_m, :ap_paterno_m, :ap_materno_m, :grado_m, :grupo_m, :telefono_m, :direccion_m)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@alumnos = Alumno.all
  end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maestros_helper.rb
module MaestrosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/alumnos/_form.html.erb
  
  <%= form_for(@alumno) do |f| %>
  <% if @alumno.errors.any? %>
    <div class="btn btn-warning" >
      <h5><%= pluralize(@alumno.errors.count, "errore") %> impiden que el registro sea guardado:</h5>

      <ul>
      <% @alumno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
<div class="form-panel">

   <h5 class="titulo_form">Introdusca cuidadosamente la información del alumno: </h5> 

  <div> <%=image_tag("student1.png", :size => "180x180", class: "student_icon")%> </div>   


  <%= f.text_field :nombre,:placeholder=>"Nombre(s) del Alumno" , :size=>"30", :class=>"formulario" %>


  <%= f.text_field :ap_paterno,:placeholder=>"Apellido Paterno", :size=>"25", :class=>"formulario" %>
  
 
  <%= f.text_field :ap_materno,:placeholder=>"Apellido Materno", :size=>"25", :class=>"formulario" %>


<div class="separa_radio">
  <%= f.label "Sexo:" , :class=>"formulario_sexo" %>
  <%=f.radio_button :sexo,'Masculino', :checked => "true"%>
  <%= f.label :sexo, 'Masculino', :class=>"formulario_masculino"%>
  <%=f.radio_button :sexo,'Femenino'%>
  <%= f.label :sexo, 'Femenino' %>

    <%= f.label "Grado" , :class=>"formulario_grado"%>
    <%= f.select :grado, {1=>"1",2=>"2",3=>"3",4=>"4",5=>"5",6=>"6"} %>

    <%= f.label "Grupo"  ,:class=>"formulario_grupo"%>
    <%= f.select :grupo, {"A"=>"A","B"=>"B","C"=>"C","D"=>"D"} %>

</div>
  
    <%= f.text_field :curp,:placeholder=>"CURP",:size=>"30",:class=>"formulario"  %>
    <%= f.text_field :fecha_nacimiento,:placeholder=>"Fecha de Nacimiento",:size=>"25",:class=>"formulario"   %>
 
    <h5 id="tutor" > <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
  Datos del Tutor:</h5>

    <%= f.text_field :nombre_tutor,:placeholder=>"Nombre(s) del Tutor",:size=>"30",:class=>"formulario" %>

    <%= f.text_field :ap_paterno_tutor, :placeholder=>"Apellido Paterno" ,:size=>"25",:class=>"formulario"%>
  
    <%= f.text_field :ap_materno_tutor, :placeholder=>"Apellido Materno",:size=>"25",:class=>"formulario" %>
  
    <div class="formulario2">
      
      <%= f.text_field :direccion,:placeholder=>"Dirección",:size=>"45", :class=>"formulario" %>
  
      <%= f.text_field :telefono,:placeholder=>"Teléfono",:size=>"25" , :class=>"formulario"%>

    </div>
    <div style="float: left; margin-right: 30px; margin-left: 360px;"> <%= f.submit "Guardar Registro",:class=>"btn btn-primary" %></div>
   
<% end %>

    <div class="btn btn-info"> <%= link_to 'Regresar', alumnos_path %>  </div>


  </div>

app/views/alumnos/busqueda.html.erb
<div style="margin-bottom: 10px; margin-top: 10px;">
  <p class="label label-warning"></p><%= notice %></p>
</div>
 
                <div class="row mt">
                  <div class="col-md-12">
                      <div class="content-panel">
                          <table class="table table-striped table-advance table-hover">
                            <div style="width: 600px;">
                            <h4 style="float: left;"><i class="fa fa-angle-right"></i>Búsqueda Rápida de Alumnos</h4>
                            </div>
                               
                            <div class="alert alert-warning" style="margin-left: 400px; text-align: center; margin-right: 50px">
                              <p>Introdusca el Nombre del Alumno para Iniciar la Búsqueda de Resultados:</p>
                              <%= form_tag({:controller => "alumnos", :action => "busqueda"}, :method => :get) do %>
                              <%=text_field_tag :nombre, nil, placeholder: 'Nombre',size:30%>
                              <%=text_field_tag :ap_paterno, nil, placeholder: 'Apellido Paterno',size:20%>
                              <%=text_field_tag :ap_materno, nil, placeholder: 'Apellido Materno',size:20%>
                              <%= submit_tag "Buscar", :class=>"btn btn-primary btn-sm"%>
                              <% end %>
                             
                            </div>

                            

                            <hr style="clear: left;">
                              <thead>
                              <tr>
                                  <th><i class=" fa fa-edit"></i> Nombre</th>
                                  <th><i class=" fa fa-edit"></i> Apellido Paterno</th>
                                  <th><i class=" fa fa-edit"></i> Apellido Materno</th>
                                  <th><i class=" fa fa-edit"></i> CURP</th>
                                  <th><i class=" fa fa-edit"></i> Grado</th>
                                  <th><i class=" fa fa-edit"></i> Grupo</th>

                                  <th></th>
                              </tr>
                              </thead>
                              <tbody>
                                <% @alumnos.each do |alumno| %>
                              <tr>
                                  <td><%= alumno.nombre %></td>
                                  <td><%= alumno.ap_paterno %></td>
                                  <td><%= alumno.ap_materno %></td>
                                  <td><%= alumno.curp %></td>
                                  <td><%= alumno.grado %></td>
                                  <td><%= alumno.grupo %></td>
                                  <td>
                                      <div class="btn btn-success btn-xs"><i class="fa fa-check aria-hidden="true""></i><%= link_to ' Ver', alumno %></div>
                                      <div class="btn btn-primary btn-xs"><i class="fa fa-pencil aria-hidden="true""><%= link_to ' Editar', edit_alumno_path(alumno) %></i></div>
                                      <div class="btn btn-danger btn-xs"><i class="fa fa-trash-o aria-hidden="true""></i><%= link_to ' Eliminar', alumno, method: :delete, data: { confirm: '¿Eliminar elemento seleccionado?' } %></div>
                                  </td>
                              </tr>
                              <% end %>
                              </tbody>
                          </table>
                      </div><!-- /content-panel -->
                  </div><!-- /col-md-12 -->
              </div><!-- /row -->

app/views/alumnos/edit.html.erb
<h4><i class="fa fa-angle-right"></i> Editar la Información del Alumno Registrado</h4>

<%= render 'form' %>

<div style="margin-bottom: 158px;"></div>

app/views/alumnos/filtro.html.erb
<div style="margin-bottom: 10px; margin-top: 10px;">
  <p class="label label-warning"></p><%= notice %></p>
</div>
 









                <div class="row mt">
                  <div class="col-md-12">
                      <div class="content-panel">
                          <table class="table table-striped table-advance table-hover">
                            <div style="width: 600px;">
                            <h4 style="float: left;"><i class="fa fa-angle-right"></i> Búsqueda de Alumnos por Salón</h4>
                            </div>
                            
                            	<div class="alert alert-warning" style="margin-left: 550px; text-align: center; margin-right: 50px">
									<p>Seleccione el grado y grupo para filtrar el resultado de alumnos inscritos:</p>
									<%= form_tag({:controller => "alumnos", :action => "filtro"}, :method => :get) do %>
									<%=label_tag "Grado:"%>
									<%=  select_tag :grado,options_for_select([ "1", "2", "3","4","5","6"],"1")  %>
									<%=label_tag "Grupo:"%>
									<%=  select_tag :grupo,options_for_select([ "A", "B", "C","D"],"A")  %>
									<%= submit_tag "Filtrar", :class=>"btn btn-primary btn-sm"%>
									<% end %>
								</div>

                            

                            <hr style="clear: left;">
                              <thead>
                              <tr>
                                  <th><i class=" fa fa-edit"></i> Nombre</th>
                                  <th><i class=" fa fa-edit"></i> Apellido Paterno</th>
                                  <th><i class=" fa fa-edit"></i> Apellido Materno</th>
                                  <th><i class=" fa fa-edit"></i> CURP</th>
                                  <th><i class=" fa fa-edit"></i> Grado</th>
                                  <th><i class=" fa fa-edit"></i> Grupo</th>

                                  <th></th>
                              </tr>
                              </thead>
                              <tbody>
                                <% @alumnos.each do |alumno| %>
                              <tr>
                                  <td><%= alumno.nombre %></td>
                                  <td><%= alumno.ap_paterno %></td>
                                  <td><%= alumno.ap_materno %></td>
                                  <td><%= alumno.curp %></td>
                                  <td><%= alumno.grado %></td>
                                  <td><%= alumno.grupo %></td>
                                  <td>
                                      <div class="btn btn-success btn-xs"><i class="fa fa-check aria-hidden="true""></i><%= link_to ' Ver', alumno %></div>
                                      <div class="btn btn-primary btn-xs"><i class="fa fa-pencil aria-hidden="true""><%= link_to ' Editar', edit_alumno_path(alumno) %></i></div>
                                      <div class="btn btn-danger btn-xs"><i class="fa fa-trash-o aria-hidden="true""></i><%= link_to ' Eliminar', alumno, method: :delete, data: { confirm: '¿Eliminar elemento seleccionado?' } %></div>
                                  </td>
                              </tr>
                              <% end %>
                              </tbody>
                          </table>
                      </div><!-- /content-panel -->
                  </div><!-- /col-md-12 -->
              </div><!-- /row -->

app/views/alumnos/index.html.erb
<div style="margin-bottom: 10px; margin-top: 10px;">
  <p class="label label-warning"></p><%= notice %></p>
</div>
 



                <div class="row mt">
                  <div class="col-md-12">
                      <div class="content-panel">
                          <table class="table table-striped table-advance table-hover">
                            <div style="width: 600px;">
                            <h4 style="float: left;"><i class="fa fa-angle-right"></i> Lista General de Alumnos Registrados</h4>
                            </div>

                            <div id="nuevo" style="padding-left: 1000px; "><a href=http://localhost:3000/alumnos/new/><%=image_tag("adduser.png", :size => "40x40")%></a></div>

                            <hr style="clear: left;">
                              <thead>
                              <tr>
                                  <th><i class=" fa fa-edit"></i> Nombre</th>
                                  <th><i class=" fa fa-edit"></i> Apellido Paterno</th>
                                  <th><i class=" fa fa-edit"></i> Apellido Materno</th>
                                  <th><i class=" fa fa-edit"></i> CURP</th>
                                  <th><i class=" fa fa-edit"></i> Grado</th>
                                  <th><i class=" fa fa-edit"></i> Grupo</th>

                                  <th></th>
                              </tr>
                              </thead>
                              <tbody>
                                <% @alumnos.each do |alumno| %>
                              <tr>
                                  <td><%= alumno.nombre %></td>
                                  <td><%= alumno.ap_paterno %></td>
                                  <td><%= alumno.ap_materno %></td>
                                  <td><%= alumno.curp %></td>
                                  <td><%= alumno.grado %></td>
                                  <td><%= alumno.grupo %></td>
                                  <td>
                                      <div class="btn btn-success btn-xs"><i class="fa fa-check aria-hidden="true""></i><%= link_to ' Ver', alumno %></div>
                                      <div class="btn btn-primary btn-xs"><i class="fa fa-pencil aria-hidden="true""><%= link_to ' Editar', edit_alumno_path(alumno) %></i></div>
                                      <div class="btn btn-danger btn-xs"><i class="fa fa-trash-o aria-hidden="true""></i><%= link_to ' Eliminar', alumno, method: :delete, data: { confirm: '¿Eliminar elemento seleccionado?' } %></div>
                                  </td>
                              </tr>
                              <% end %>
                              </tbody>
                          </table>
                      </div><!-- /content-panel -->
                  </div><!-- /col-md-12 -->
              </div><!-- /row -->

app/views/alumnos/new.html.erb
  






	<h4><i class="fa fa-angle-right"></i> Formulario para el Registro de un Nuevo Alumno</h4>
 	<%= render 'form' %>
	
	<div style="margin-bottom: 158px;"></div>

app/views/alumnos/show.html.erb
<div style="margin-bottom: 10px; margin-top: 10px;">
  <p class="label label-warning"></p><%= notice %></p>
</div>

  <h4><i class="fa fa-angle-right"></i> Información Completa del Alumno</h4>

<div class="form-panel">

  <div> <%=image_tag("show2.png", :size => "180x180", class: "student_icon")%> </div> 
  <h3 class="titulos"><i class="fa fa-user" aria-hidden="true"></i>

  Datos del Alumno</h3>

  <strong class="formulario_2">Nombre:</strong>
  <%= @alumno.nombre %>
  <%= @alumno.ap_paterno %>
  <%= @alumno.ap_materno %>

  <div>
    <strong class="formulario_2">Sexo:</strong>
    <%= @alumno.sexo %>
    <strong class="formulario3_2">Curp:</strong>
    <%= @alumno.curp %>
  </div>


  <div>
    <strong class="formulario_2">Fecha Nacimiento:</strong>
    <%= @alumno.fecha_nacimiento %>

    <strong class="formulario3_2">Grado:</strong>
    <%= @alumno.grado %>

    <strong class="formulario3_2" >Grupo:</strong>
    <%= @alumno.grupo %>
  </div>



  <h3 class="titulos"><i class="fa fa-user" aria-hidden="true"></i> Datos del Tutor</h3>


  <strong class="formulario_2">Nombre del Tutor:</strong>
  <%= @alumno.nombre_tutor %>
  <%= @alumno.ap_paterno_tutor %>
  <%= @alumno.ap_materno_tutor %>


  <div class="espacio-direccion">
    <strong class="formulario_2">Dirección:</strong>
    <%= @alumno.direccion %>

    <strong class="formulario3_2">Teléfono:</strong>
    <%= @alumno.telefono %>
  </div>
</div>


<div class="botones_show">
  
  <%= link_to 'Editar', edit_alumno_path(@alumno),:class=>"btn btn-info" %> 
  <%= link_to 'Regresar', alumnos_path ,:class=>"btn btn-warning"%>
</div>

app/views/alumnos/tutor.html.erb
	<h4><i class="fa fa-angle-right"></i> Alumnos que han sido Registrados con el Tutor Seleccionado</h4>

app/views/maestros/_form.html.erb
  
<%= form_for(@maestro) do |f| %>
  <% if @maestro.errors.any? %>
    <div class="btn btn-warning">
      <h5><%= pluralize(@maestro.errors.count, "errore") %> impiden que el registro sea guardado:</h5>

      <ul>
      <% @maestro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="form-panel">
  
  <h5 class="titulo_form" >Introdusca cuidadosamente la información del maestro: </h5> 

  <div> <%=image_tag("teacher1.png", :size => "180x180", class: "student_icon")%> </div>
  <div style="margin-bottom: 40px;"></div>   

  <%= f.text_field :nombre_m,:placeholder=>"Nombre(s) del Maestro" , :size=>"30", :class=>"formulario"%>

  <%= f.text_field :ap_paterno_m,:placeholder=>"Apellido Paterno", :size=>"25", :class=>"formulario" %>
 
  <%= f.text_field :ap_materno_m,:placeholder=>"Apellido Materno", :size=>"25", :class=>"formulario" %>


  <div>  <h3 class="titulos" style="margin-bottom: 20px;"><i class="fa fa-book" aria-hidden="true"></i> Salón a Cargo: </h3>
  </div>

  <div class="separa_radio">
    <%= f.label "Grado" , :class=>"formulario_grado"%>
    <%= f.select :grado_m, {1=>"1",2=>"2",3=>"3",4=>"4",5=>"5",6=>"6"} %>

    <%= f.label "Grupo"  ,:class=>"formulario_grupo"%>
    <%= f.select :grupo_m, {"A"=>"A","B"=>"B","C"=>"C","D"=>"D"} %>
  </div>
  
   
  <div class="formulario2">
      
    <%= f.text_field :direccion_m,:placeholder=>"Dirección",:size=>"45", :class=>"formulario" %>
  
    <%= f.text_field :telefono_m,:placeholder=>"Teléfono",:size=>"25" , :class=>"formulario"%>

  </div>
  <div style="margin-bottom: 40px;"></div>

</div>

  <div style="float: left; margin-right: 30px; margin-left: 360px;"> <%= f.submit "Guardar Registro",:class=>"btn btn-primary" %>
  </div>
   
  <% end %>

  <div class="btn btn-info"> <%= link_to 'Regresar', maestros_path %>  </div>

  <div style="margin-bottom:143px;"></div>

app/views/maestros/edit.html.erb
<h4><i class="fa fa-angle-right"></i> Editar la Información del Maestro Registrado</h4>

<%= render 'form' %>

	

app/views/maestros/index.html.erb
  
<div style="margin-bottom: 10px; margin-top: 10px;">
  <p class="label label-warning"></p><%= notice %></p>
</div>


<div class="row mt">
                  <div class="col-md-12">
                      <div class="content-panel">
                          <table class="table table-striped table-advance table-hover">
                            <div style="width: 600px;">
                            <h4 style="float: left;"><i class="fa fa-angle-right"></i> Lista General de  Maestros Registrados</h4>
                            </div>
                               <div id="nuevo" style="padding-left: 1000px; "><a href=http://localhost:3000/maestros/new/><%=image_tag("adduser.png", :size => "40x40")%></a></div>


                            

                            <hr style="clear: left;">
                              <thead>
                              <tr>
                                  <th><i class=" fa fa-edit"></i> Nombre</th>
                                  <th><i class=" fa fa-edit"></i> Apellido Paterno</th>
                                  <th><i class=" fa fa-edit"></i> Apellido Materno</th>
                                  <th><i class=" fa fa-edit"></i> Grado</th>
                                  <th><i class=" fa fa-edit"></i> Grupo</th>
                                  <th><i class=" fa fa-edit"></i> Teléfono</th>


                                  <th></th>
                              </tr>
                              </thead>
                              <tbody>
                                <% @maestros.each do |maestro| %>
                              <tr>
                                  <td><%= maestro.nombre_m %></td>
                                  <td><%= maestro.ap_paterno_m %></td>
                                  <td><%= maestro.ap_materno_m %></td>
                                  <td><%= maestro.grado_m %></td>
                                  <td><%= maestro.grupo_m %></td>
                                  <td><%= maestro.direccion_m %></td>
                                  <td>
                                      <div class="btn btn-success btn-xs"><i class="fa fa-check aria-hidden="true""></i><%= link_to ' Ver', maestro %></div>
                                      <div class="btn btn-primary btn-xs"><i class="fa fa-pencil aria-hidden="true""><%= link_to ' Editar', edit_maestro_path(maestro) %></i></div>
                                      <div class="btn btn-danger btn-xs"><i class="fa fa-trash-o aria-hidden="true""></i><%= link_to ' Eliminar', maestro, method: :delete, data: { confirm: '¿Eliminar elemento seleccionado?' } %></div>
                                  </td>
                              </tr>
                              <% end %>
                              </tbody>
                          </table>
                      </div><!-- /content-panel -->
                  </div><!-- /col-md-12 -->
              </div><!-- /row -->

app/views/maestros/show.html.erb
<div style="margin-bottom: 10px; margin-top: 10px;">
  <p class="label label-warning"></p><%= notice %></p>
</div>

<h4><i class="fa fa-angle-right"></i> Información Completa del Maestro</h4>

<div class="form-panel">

  <div> <%=image_tag("show2.png", :size => "180x180", class: "student_icon")%> </div> 
  <h3 class="titulos" style="margin-bottom: 20px;"><i class="fa fa-user" aria-hidden="true"></i>

  Datos del Maestro</h3>

  <strong class="formulario_2">Nombre:</strong>
  
  <%= @maestro.nombre_m %>
  <%= @maestro.ap_paterno_m %>
  <%= @maestro.ap_materno_m %>

  <div style="margin-bottom: 10px;">
  </div>

  <div class="espacio-direccion">
    <strong class="formulario_2">Dirección:</strong>
    <%= @maestro.direccion_m %>

    <strong class="formulario3_2">Teléfono:</strong>
    <%= @maestro.telefono_m %>
  </div>
  <h3 class="titulos" style="margin-bottom: 20px;"><i class="fa fa-book" aria-hidden="true"></i> Salón a Cargo: </h3>

  <div style="margin-bottom: 20px;">


    <strong class="formulario3_2">Grado:</strong>
    <%= @maestro.grado_m %>

    <strong class="formulario3_2" >Grupo:</strong>
    <%= @maestro.grupo_m %>
  </div>
</div>

<div style="margin-bottom: 20px;"> </div>
<div class="botones_show">
  
  <%= link_to 'Editar', edit_maestro_path(@maestro),:class=>"btn btn-info" %> 
  <%= link_to 'Regresar', maestros_path ,:class=>"btn btn-warning"%>
</div>

app/views/welcome/index.html.erb
<div>Inicio</div>